name: chocolate-joe
services:
  telegram-bot:
    build: .
    env_file:
      - .env
    restart: unless-stopped
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_POLL_INTERVAL=300
      - WATCHTOWER_INCLUDE_RESTARTING=true
    restart: unless-stopped

  redis:
    image: redis:alpine
    ports:
      - 6379:6379
    restart: unless-stopped
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
