name: Build and Push Docker Image

on:
  push:
    branches: [main, fully-auto-deploy]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get commit info
        id: commit
        run: |
          echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
          echo "message=$(git log -1 --pretty=%s | tr -d '\n' | tr '[:space:]/' '_' | cut -c1-40)" >> $GITHUB_OUTPUT

      - name: Build services with Docker Compose (multi-arch)
        run: |
          # Enable buildx in compose
          export DOCKER_BUILDKIT=1
          export COMPOSE_DOCKER_CLI_BUILD=1

          # Build all services for multiple platforms
          docker compose build --no-cache --progress=plain \
            --build-arg BUILDKIT_INLINE_CACHE=1

      - name: Push images with rich tags
        run: |
          BASE_IMAGE="${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}"

          TAGS=(
            "latest"
            "${{ steps.commit.outputs.sha_short }}"
            "${{ github.sha }}"
            "branch-${{ github.ref_name }}"
          )

          if [[ ${{ github.ref }} == refs/tags/* ]]; then
            TAGS+=("${{ github.ref_name }}")
          fi

          for tag in "${TAGS[@]}"; do
            docker tag "$BASE_IMAGE:latest" "$BASE_IMAGE:$tag"
            docker push "$BASE_IMAGE:$tag"
          done
